<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f0773a18-35a4-4b6f-a3bd-441a73d8551f</testSuiteGuid>
   <testCaseLink>
      <guid>2c07d0e3-a5ca-46d0-bc86-b2e423244a4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-JObSubmission</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77238d6-95dd-4d45-a885-f2c3fbb097d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddf28354-bcd5-40b0-b7a7-b731ff0fae86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a526fc23-b96c-4e37-80e2-a120f767c6fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-GenericActions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05d426bf-c5e1-4fda-b00f-022bbf0e193f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17e8bb60-f65f-41c8-aa10-bfbe20b0d480</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1afd078c-0857-4429-9df2-6575f6736c38</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-FileOps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee8c6b5b-4cd6-4f2f-a3ea-9d5457cde594</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e02443f-7bc7-4a60-a9ca-7dea0ebfdc7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>134e2494-92b7-4b62-ab67-6b2f4e1c421b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-GenericActions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;Files&quot;</value>
         <variableId>05d426bf-c5e1-4fda-b00f-022bbf0e193f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17e8bb60-f65f-41c8-aa10-bfbe20b0d480</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
