<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>testRun</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e7def78f-5f8e-4830-887a-1d6960f0e70f</testSuiteGuid>
   <testCaseLink>
      <guid>e4d07ae2-da78-42a5-a2e7-9e048b187248</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FilesModule/Create_folder_old</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;tile&quot;</value>
         <variableId>ee5dd06b-fe53-4cd7-b0ae-9d5aa0e1949d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;tile view&quot;</value>
         <variableId>7d839b7d-abd5-48a9-9050-61b7d5242a7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44855711-d67d-4932-bf58-df854a599660</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df2f0a9c-c10b-4bba-9428-6c66d4dd6cd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FilesModule/Create_folder_old</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;list&quot;</value>
         <variableId>ee5dd06b-fe53-4cd7-b0ae-9d5aa0e1949d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>&quot;list view&quot;</value>
         <variableId>7d839b7d-abd5-48a9-9050-61b7d5242a7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44855711-d67d-4932-bf58-df854a599660</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
